language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "schnatterer-github"
    branches:
      - master
      - develop

script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'